Determine whether to create an issue using a count check

diff --git a/.github/workflows/daily-vul-scan.yml b/.github/workflows/daily-vul-scan.yml
--- a/.github/workflows/daily-vul-scan.yml
+++ b/.github/workflows/daily-vul-scan.yml
@@ -51,8 +51,21 @@ jobs:
           template: "@.github/ISSUE_TEMPLATE/trivy-results.tpl"
           output: ${{ env.TRIVY_RESULTS_MARKDOWN }}
 
+      - name: Extract total count of vulnerabilities
+        id: extract-total-cnt-of-vulns
+        run: |
+          if [[ $(cat "${{ env.TRIVY_RESULTS_MARKDOWN }}") =~ Total\ count\ of\ vulnerabilities:\ ([0-9]+) ]]; then
+            result=${BASH_REMATCH[0]}
+            echo "$result"
+            total_cnt_of_vulns=${BASH_REMATCH[1]}
+            echo "total_cnt_of_vulns=$total_cnt_of_vulns" >> "$GITHUB_OUTPUT"
+          else
+            echo "Error: Failed to extract total count of vulnerabilities"
+            exit 1
+          fi
+
       - name: Insert YAML front matter into the results markdown
-        if: always()
+        if: ${{ fromJson(steps.extract-total-cnt-of-vulns.outputs.total_cnt_of_vulns) > 0 }}
         run: |
           sed -i '1i\
           ---\
@@ -62,8 +75,8 @@ jobs:
           ' "${{ env.TRIVY_RESULTS_MARKDOWN }}"
 
       - name: Create or update the trivy results issue
+        if: ${{ fromJson(steps.extract-total-cnt-of-vulns.outputs.total_cnt_of_vulns) > 0 }}
         uses: JasonEtco/create-an-issue@v2
-        if: always()
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
